// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAuYqvTDn1-4vG31vPNAUlqYbNRsCJXRPs",
    authDomain: "civic-link-878a6.firebaseapp.com",
    projectId: "civic-link-878a6",
    storageBucket: "civic-link-878a6.firebasestorage.app",
    messagingSenderId: "361787266234",
    appId: "1:361787266234:web:fb9a44e14dbd15d0f15e83",
    measurementId: "G-SXCYLHY50R",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFfghM0Cpz7IociyndWgHkO0afABkS9I',
    appId: '1:625527546721:android:d1feebe8e4deac88339b20',
    messagingSenderId: '625527546721',
    projectId: 'civiclink-mumbai',
    storageBucket: 'civiclink-mumbai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzCeYbacO2PRoWxbOyfy2rcIoKheTn8Uc',
    appId: '1:625527546721:ios:ba637f09b12470f0339b20',
    messagingSenderId: '625527546721',
    projectId: 'civiclink-mumbai',
    storageBucket: 'civiclink-mumbai.firebasestorage.app',
    iosBundleId: 'com.example.civiclinkMumbai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzCeYbacO2PRoWxbOyfy2rcIoKheTn8Uc',
    appId: '1:625527546721:ios:ba637f09b12470f0339b20',
    messagingSenderId: '625527546721',
    projectId: 'civiclink-mumbai',
    storageBucket: 'civiclink-mumbai.firebasestorage.app',
    iosBundleId: 'com.example.civiclinkMumbai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAphvQqenvrCGg5H7jqiDH3TJO5bTcglA8',
    appId: '1:625527546721:web:9021137183d44738339b20',
    messagingSenderId: '625527546721',
    projectId: 'civiclink-mumbai',
    authDomain: 'civiclink-mumbai.firebaseapp.com',
    storageBucket: 'civiclink-mumbai.firebasestorage.app',
  );
}